//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace util
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int AddressID { get; set; }
        public string MSACode { get; set; }
        public string CountryCode { get; set; }
        public string StateProvCode { get; set; }
        public string CountyRegionName { get; set; }
        public string CityName { get; set; }
        public string Address1 { get; set; }
        public string Address1SoundexCode { get; set; }
        public string Address2 { get; set; }
        public string PostalZipCode { get; set; }
        public string PostalCodeExtension { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string AddrStandardCode { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string Version { get; set; }
        public string MatchCode { get; set; }
        public string GeocodeType { get; set; }
        public Nullable<int> EnterpriseAddressID { get; set; }
        public string BuildingNumber { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
    }
}
